# Generated by Django 3.2.6 on 2021-08-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0002_auto_20210813_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
    ]
