# Generated by Django 3.2.6 on 2021-08-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0003_remove_snippet_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
