# Generated by Django 3.2.6 on 2021-08-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
