# Generated by Django 3.2.6 on 2021-08-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0007_auto_20210819_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='info',
        ),
    ]
