# Generated by Django 3.2.6 on 2021-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0009_company_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
